### ISSUE TITLE
Compiling v7.2.0 failed : adjust Makefile (solved)

### ISSUE THREAD

**Issue by tissatussa** [Vast342/Clarity#109]
After copying your v7.2.0 source by `git clone` (PR 107) i got errors when compiling. But i solved them, here's how.

On the `CXXFLAGS := ...` line you use the option `-std=c++20`, so this requires a modern `clang` version. On my OS (Xubuntu 22.04) the default clang version is 14 : i changed that by setting `CXX := clang-17`.
But this didn't solve some other errors. Looking for answers, even consulting ChatGPT, i found you made a basic mistake : `clang++` should be used, in my case `clang++-17` !

I also got many (same) warnings `argument unused during compilation: '-fuse-ld=lld' [-Wunused-command-line-argument]`.
I discovered this option isn't needed (or is it?) so i safely removed it from the `CXXFLAGS := ...` line.

Other minor adjustments :
- `LDFLAGS :=` : this is empty, and used only once, so i removed that also.
- `PGO_DIR` isn't defined and also not used (only at `clean:`), so i removed it.
- same for `pgo-generate` (at `.PHONY:`) : not used, so i removed it.

Besides that, i solved this warning (i only got one) :

```
src/external/fathom/tbprobe.cpp:2463:41: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
 2463 |   if (popcount(pos->white | pos->black) <= cardinalityDTM) {
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~
```

like this :

```
if (static_cast<unsigned int>(popcount(pos->white | pos->black)) <= static_cast<unsigned int>(cardinalityDTM)) {
```

Maybe i'm mistaken at some points, then please correct me.

After these changes the compilation went well and it created a binary of size 1.7 Mb which runs fine in CuteChess GUI.
And it plays a good game !

Btw. you may look at my ChatGPT session to solve the errors and warnings : https://chatgpt.com/share/93580c50-3ec8-4091-8524-692befc2f184
But this 'conversation' contains lots of useless (?) tries and code constructs, upto to moment i discovered `clang++` is needed .. anyhow, this way i learned a lot !

**Comment by Vast342** [comment]
Ah thank you, I had forgotten about the ``clang++`` issue, I fixed it as part of a branch quite a while ago but the main change failed so I had forgotten about it.

``-fuse-ld=lld`` is used for me, it prevents a few issues that had been happening on a few of the PCs I run games on.

Other than that, thanks for reporting the issues, I'll get to fixing those soon.

**Comment by tissatussa** [comment]
i'm also learning all the time .. that's one of the reasons i figured it out and wrote you .. this GitHub Issue is my archive also : "i once wrote about that in some Clarity Issue, if i remember correctly" :-)

whenever you create new code, how do you test / use it ? By compiling that new source into a binary and perform tests ? Then, which Makefile do you use to create the binary ? And what can we do with that CMakeLists.txt ? Executing `cmake .` creates a `makefile` but it's invalid, it gives errors .. this almost never happened with me, i rarely have troubles with `cmake` - i'm only on Linux.

a few other points, which i didn't mention in this Issue.
- while compiling i see some `bmi2` file, although `makefile` has no option like `-mbmi2` .. can we add it ? My notebook can "do bmi2" but maybe your code won't get any faster with it.
- same for avx2
- pgo : did you ever include this ? What is `PGO_DIR` ?

the `lld` option wasn't clear to me but i'm beginning to understand its meaning and function .. when i changed to clang++-17, i also had to change the lld option into `-fuse-ld=lld-17` to get it working anyhow, and for that i asked ChatGPT to assist (i managed, see my link) .. adding lld might be useful, i'm not familiar with such coding, it's close to the hardware - i only use those Makefiles and sometimes have to repair them.

in this regard, i just found this entry from 2019, HTH
https://patchwork.kernel.org/project/linux-kbuild/patch/20190211193008.24101-3-ndesaulniers@google.com/

_Makefile: lld: tell clang to use lld
This is needed because clang doesn't select which linker to use based on
$LD but rather -fuse-ld=lld. This is problematic especially for
cc-ldoption, which checks for linker flag support via invoking the
compiler, rather than the linker._

lastly that recent Chess Diary entry .. it's for Android and i have no clue there, but anyhow :
https://chessengines.blogspot.com/2024/07/android-chess-engines-tournament-by.html
_Tournament of new engine versions for Android. Three engines scored the same number of points and shared places 1-3: Alexandria 7.0.0, Obsidian 13.0 and CorChess 240703. Surprisingly, Corchess did not win the tournament, but lost (on time) the game against the Alexandria engine.
Clarity 7.2.0 had trouble starting (timed out after a few moves) so we are removing it from further testing._
