### ISSUE TITLE
Crashes on quit

### ISSUE THREAD

**Issue by jimablett** [Vast342/Clarity#56]
Engine crashes when exiting - threads not cleaned up properly.

changing all instances of std::thread with std::jthread fixes the problem.

JA.

**Comment by Vast342** [comment]
I will fix and test this later today, thank you for pointing this out. How were you able to differentiate the engine crashing vs the engine shutting down properly?

**Comment by Vast342** [comment]
I have now tested the proposed solution and it still crashes while exiting, so perhaps there is another problem.

**Comment by Vast342** [comment]
I should clarify that it didn't just crash in the intended way of shutting off, I put the line ``std::cout << "goodbye" << std::endl;`` between the thread joining and returning 0 and that message wasn't sent.
