### ISSUE TITLE
Consider new release file-naming scheme.

### ISSUE THREAD

**Issue by tpasfieldERAU** [Vast342/Clarity#62]
Consider using a file-naming scheme for releases that states the overall version of Clarity. It currently isn't possible to discern between different releases of the engine based on file name alone. The v1, v2, v3, v4, etc. structure works, but it needs to clarify which overall engine version is present.

Keeping it separated by micro-architecture levels is good, keep that.

Idea:
- Clarity_v5.1.0_x86-64-v1.exe

**Comment by Vast342** [comment]
This has now been done on all of the releases, and will continue to be done in the future.
