### ISSUE TITLE
Please add ARMv9.2, SVE2, Dot Product and Neon support

### ISSUE THREAD

**Issue by Chess321** [Vast342/Clarity#78]
It's sad that it's not possible to compile the newest version on Android and Linux devices.

**Comment by Vast342** [comment]
What is preventing builds for Android or Linux?

**Comment by Vast342** [comment]
I build on Linux for the majority of my testing, and others have built Clarity on Android, Linux with an ARM CPU, and Apple M2. There does not seem to be any issue preventing it from being built.
